// Example Table:
Example:
Load
 RowNo()                                 as Example_Integer,
 Round(Rand(),0.01)                      as Example_Number,
 Round(Rand(),0.0001)                    as Example_Number_Dec4,
 'String here from ' & RowNo() & ' line' as Example_String,
 Now()                                   as Example_Now
AutoGenerate(10000);




/*
 CreateSQLTables: Create a Table on SQL Database "if not exists"
 Call CreateSQLTables('[Table]', '[Path]', '[File]');
*/
Call CreateSQLTables('Example', '$(vFolder)', 'Example');


/*
 CreateSQLInsert: Insert data with SQL standards (slow-medium speed)
 Insert Method:   Call CreateSQLInsert('Qlik_Table', 'Database_Table', [Mode], '[Row Size]');
*/
Call CreateSQLInsert('Example', 'example', 0, 5000);


/*
 CreateCSVInsert: Insert data with 'CSV' file (fast-superfast speed)
 CSV Method:      Call CreateCSVInsert('Qlik_Table', 'Database_Table', [Mode], '[Path]', '[Path_Files]', '[Format]', '[Delimiter]');
*/
// Call CreateCSVInsert('Example', 'example', 0, '$(vFolder)', 'G:/QVD', 'csv', ';');